export const mlRole = {
  slug: 'machine-learning-engineer-researcher',
  title: 'Machine Learning Engineer / Researcher',
  location: 'London, UK',
  employmentType: 'Full-time',
  rightToWork: 'Applicants must already have the right to work in the UK; visa sponsorship is not currently available.',
  responsibilities: [
    'Develop and improve machine learning models for weather forecasting and extreme-event prediction.',
    'Run experiments with Qronon models for specific clients and projects.',
    'Keep up to date with relevant machine learning research and implement promising methods in the Qronon codebase.',
    'Deploy models in live environments and improve them using evidence from real-world operation.',
    'Help architect high-volume data pipelines and collect data alongside the data team.',
    'Help solve forecasting and optimisation problems across energy and other weather-sensitive sectors.',
  ],
  qualifications: [
    'A passion for helping the world reduce carbon emissions.',
    'Strong foundations in machine learning, including modern deep-learning architectures and training methods.',
    'Strong Python and Git experience, with particular interest in JAX.',
    'Experience working with large, high-dimensional or spatiotemporal datasets.',
    'Good intuition for real-world data: how it can fail, how to identify those failures and how to address them.',
    'A sound understanding of statistical evaluation, uncertainty and the difference between an impressive demonstration and a genuinely better predictive model.',
    'Enthusiasm for learning, experimentation and rigorous model comparison.',
    'Clear written and verbal communication, including the ability to explain technical trade-offs to specialist and non-specialist colleagues.',
    'An interest in working across a cross-functional team, from research and data engineering to back-end and front-end implementation.',
  ],
  beneficial: [
    'Experience contributing to open-source code or communities.',
    'An interest in writing or speaking about technical work.',
    'Machine learning for weather, climate, Earth observation or another physical dynamical system.',
    'Graph neural networks, transformers, neural operators, state-space models, generative or diffusion methods, or other architectures for spatiotemporal prediction.',
    'Probabilistic forecasting, ensemble methods, calibration, data assimilation or extreme-event evaluation.',
    'Atmospheric datasets and tools such as ERA5, NetCDF, Zarr, xarray or Dask.',
    'Distributed training, GPU optimisation and HPC environments such as Slurm.',
    'Numerical weather prediction, atmospheric dynamics or verification metrics used in operational forecasting.',
    'Taking a research model into an API, live product, commercial pilot or other operational setting.',
    'Publishing high-quality research or making significant contributions to strong open-source technical projects.',
    'Quantum computing, quantum machine learning or quantum-inspired optimisation. This supports Qronon’s longer-term research direction but is not required for success in the role.',
  ],
  benefits: [
    '£50,000–£65,000, based on experience and London weighting.',
    'Flexible hours.',
    'Autonomy in how you deliver your work.',
    '30 days of annual leave, excluding UK public holidays.',
    // 'Private healthcare and global travel insurance after successful completion of the probation period.',
    // '7% employer pension contribution.',
    // 'Training and development budget.',
  ],
};
