export const mlRole = {
  slug: 'machine-learning-engineer-researcher',
  title: 'Machine Learning Engineer / Researcher - Weather & Energy',
  location: 'London, UK',
  employmentType: 'Full-time',
  rightToWork: 'Applicants must already have the right to work in the UK; visa sponsorship is not currently available.',
  responsibilities: [
    'Develop and improve machine learning models for weather forecasting and extreme-event prediction.',
    'Run experiments with Qronon models for specific clients and projects.',
    'Keep up to date with relevant machine learning research and implement promising methods in the Qronon codebase.',
    'Deploy models in live environments and improve them using evidence from real-world operation.',
    'Help architect high-volume data pipelines and collect data alongside the data team.',
    'Help solve forecasting and optimisation problems across energy and other weather-sensitive sectors.',
  ],
  qualifications: [
  'Strong foundations in machine learning, including modern deep-learning architectures and training methods.',
  'Strong Python and Git experience, with experience using JAX, PyTorch or similar modern ML frameworks.',
  'Experience working with large, high-dimensional, time-series or spatiotemporal datasets.',
  'Good intuition for real-world data: how it can fail, how to identify those failures and how to address them.',
  'A sound understanding of statistical evaluation, uncertainty and the difference between an impressive demonstration and a genuinely better predictive model.',
  'Ability to take ideas from research and experimentation through rigorous validation and implementation.',
  'Clear written and verbal communication and an ability to work across research, engineering and product.',
  'Motivation to work on technically challenging problems with real-world impact.',
],
  beneficial: [
  'Machine learning for weather, climate, Earth observation or another physical dynamical system.',
  'Experience with architectures for spatiotemporal prediction, such as graph neural networks, transformers, neural operators, state-space models or generative methods.',
  'Probabilistic forecasting, ensemble methods, calibration, data assimilation or extreme-event evaluation.',
  'Experience with atmospheric or geospatial datasets and tools such as ERA5, NetCDF, Zarr, xarray or Dask.',
  'Distributed training, GPU optimisation or HPC environments such as Slurm.',
  'Numerical weather prediction, atmospheric dynamics or operational forecast verification.',
  'Taking research models into live products, APIs, commercial pilots or other operational settings.',
  'Publishing high-quality research, contributing to strong open-source projects, or communicating technical work publicly.',
  'Quantum computing, quantum machine learning or quantum-inspired methods. Relevant to Qronon’s longer-term research direction, but not required for success in the role.',
],
  benefits: [
    'Competitive salary, based on experience.',
    'Share options as part of the compensation package.',
    'Flexible hours.',
    'Autonomy in how you deliver your work.',
    '30 days of annual leave, excluding UK public holidays.',
    // 'Private healthcare and global travel insurance after successful completion of the probation period.',
    // '7% employer pension contribution.',
    // 'Training and development budget.',
  ],
};
